### ISSUE TITLE
Great job very helpful

### ISSUE THREAD

**Issue by WebCrew** [XHiddenProjects/MMV#1]
Great job Gavin and it is a way better and more feature rich then I expected - **I like it**.

At the readme is one sentence which doesn`t really translate correctly for me.

**At the setup the sentence**:
"_To start off with loading the viewers you have to make a container for the media are going to place._"

**I would be able to understand it better like this**:
To begin loading the viewers, you need to create a container for the media to be placed.

But that's just my opinion and a small thing anyway - it's quite possible that I'm just too stupid to understand the grammar properly, after all, American is only my second language.

I wish you a great day and I hope some people will find the MMV Repository and make good use of it!

**Comment by XHiddenProjects** [comment]
My English isn't that great 😂, I will fix that grammar and sentence structure.

**Comment by WebCrew** [comment]
Lol my English is more worse then yours Gavin I promise lol

I can't even say with certainty whether that was actually a grammatical error in the README, it just sounded a bit strange to me when translated, which is why I mentioned it at all. But it's entirely possible that it wasn't a grammatical error on your part at all.

I wish you a great day man :)

**Comment by XHiddenProjects** [comment]
Ok thank you
